# configuration for the s3 object qc

job_type: meta_xml_qc
#job_type: bam_qc

job_git_repo: "git@github.com:ICGC-TCGA-PanCancer/s3-data-qc-ops.git"

# production is bam-qc
job_queue_dir: test-bam-qc
