# configuration for the s3 object qc

# meta xml qc
#job_type: meta_xml_qc
#job_queue_dir: test-meta_xml_qc
#job_queue_dir: meta_xml_qc

# bam qc
# job_type: bam_qc
# job_queue_dir: test-bam_qc

# ceph transfer 
job_type: egaco_transfer
job_queue_dir: test-egaco-transfer

job_git_repo: "git@github.com:ICGC-TCGA-PanCancer/ceph_transfer_ops.git"

keep_running_even_queue_empty: true
ega_email: 
ega_password: 