# configuration for the s3 object qc

# meta xml qc
#job_type: meta_xml_qc
#job_queue_dir: test-meta_xml_qc
#job_queue_dir: meta_xml_qc

# bam qc
job_type: ceph_transfer
job_queue_dir: test-ceph-transfer

job_git_repo: "git@github.com:ICGC-TCGA-PanCancer/ceph_transfer_ops.git"
